### ISSUE TITLE
Getting Media Projection error on Android 10 when compiled with target SDK version 30

### ISSUE THREAD

**Issue by pavan142** [pavan142/ScreenX#14]
The issue only occurs when built with **(compile version: 30 and target version: 30)** and **run on Android 10**.
There are two ways out of this
* **Downgrade** the compile version and target versions to 28
* Keep the compile version and target version as 30 and don't support for devices running **Android 10**

The reason why I am even considering second option is, when the first option clearly seems best is, **Google Play store** is not allowing me to upload an **apk with target version < 29**.

**Comment by pavan142** [comment]
2021-03-22 05:21:09.210 30149-30149/com.frankenstein.screenx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.frankenstein.screenx, PID: 30149
    java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
        at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
        at com.frankenstein.screenx.capture.ScreenCaptureManager$startProjection$1.run(ScreenCaptureManager.kt:85)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
